### PR TITLE
Fixing the native build so it can find the TSL headers

### LINKED ISSUE #529: Build native codes current master fails
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04 x86\_64): Ubuntu 22.04 on x64_64
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.15.0
- Java version (i.e., the output of `java -version`): openjdk 11
- Java command line flags (e.g., GC parameters): 
- Installed from Maven Central?: No
- Bazel version (if compiling from source): 6.1.0
- GCC/Compiler version (if compiling from source): clang 14.0.0-1ubuntu1.1
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the problem**
Try to build the x86_64 native code jars for the current master of tensorflow/java (https://github.com/tensorflow/java/tree/2b6d83fd32ed1ec03e1e3468830a9ff12187fc1b)

**Provide the exact sequence of commands / steps that you executed before running into the problem**
Start ubuntu 22.04 docker image:
```
docker run -it -v $(pwd):/work -w /work ubuntu:22.04
```

Then prepare build environment for tensorflow in the running docker image:
```
TF_VERSION="v2.15.0"
apt update
apt install -y build-essential clang maven libgomp1
apt install -y python3-dev python3-pip
apt install -y pkg-config zip zlib1g-dev unzip curl tmux wget vim git htop
apt install -y openjdk-11-jdk
apt install -y liblapack3 libblas3 libhdf5-dev
pip3 install six mock numpy grpcio
pip3 install h5py
pip3 install keras_applications --no-deps
pip3 install keras_preprocessing --no-deps
pip3 install packaging

# get bazel version needed for the specific tensorflow version
git clone  https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout "${TF_VERSION}"

# install needed bazel version
BAZEL_VERSION="$(cat .bazelversion|head -n1)"
wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-dist.zip
mkdir bazel-${BAZEL_VERSION}
unzip bazel-${BAZEL_VERSION}-dist.zip -d bazel-${BAZEL_VERSION}
cd bazel-${BAZEL_VERSION}
./compile.sh
cp output/bazel /usr/local/bin/
cd ..
```

Then try to build the native code jars like this:
```
TF_JAVA_VERSION="master"
git clone https://github.com/tensorflow/java.git
cd java
git checkout ${TF_JAVA_VERSION}
mvn clean install -Djavacpp.platform.host -Dnative.build
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

The run fails in the **TensorFlow Native Library** step in tensorflow java after successfully compiling tensorflow source:
```
[ . . . ]
[13,659 / 13,664] Compiling tensorflow/compiler/mlir/python/mlir.cc; 44s local ... (3 actions running)
[13,661 / 13,664] Compiling mlir/lib/Dialect/GPU/IR/GPUDialect.cpp; 18s local
[13,662 / 13,664] [Prepa] Linking external/org_tensorflow/tensorflow/libtensorflow_cc.so.2.15.0
[13,662 / 13,664] Linking external/org_tensorflow/tensorflow/libtensorflow_cc.so.2.15.0; 1s local
[13,663 / 13,664] [Prepa] action 'SolibSymlink _solib_k8/libexternal_Sorg_Utensorflow_Stensorflow_Slibtensorflow_Ucc.so.2.15.0'
Target @org_tensorflow//tensorflow:tensorflow_cc up-to-date:
  bazel-bin/external/org_tensorflow/tensorflow/libtensorflow_cc.so.2.15.0
INFO: Elapsed time: 2031.682s, Critical Path: 313.18s
INFO: 13664 processes: 900 internal, 12764 local.
INFO: Build completed successfully, 13664 total actions
Normalizing paths
Listing /java/tensorflow-core/tensorflow-core-native/bazel-bin/external/org_tensorflow/tensorflow:
total 608732
drwxr-xr-x  6 root root      4096 Mar 15 14:34 c
drwxr-xr-x  5 root root      4096 Mar 15 14:29 cc
drwxr-xr-x  7 root root      4096 Mar 15 14:25 compiler
drwxr-xr-x 28 root root      4096 Mar 15 14:48 core
drwxr-xr-x  3 root root      4096 Mar 15 14:22 distribute
drwxr-xr-x  5 root root      4096 Mar 15 14:21 dtensor
lrwxrwxrwx  1 root root        26 Mar 15 14:49 libtensorflow_cc.so -> libtensorflow_cc.so.2.15.0
lrwxrwxrwx  1 root root        26 Mar 15 14:49 libtensorflow_cc.so.2 -> libtensorflow_cc.so.2.15.0
-r-xr-xr-x  1 root root 574062848 Mar 15 14:49 libtensorflow_cc.so.2.15.0
-r-xr-xr-x  1 root root   1078929 Mar 15 14:15 libtensorflow_cc.so.2.15.0-2.params
lrwxrwxrwx  1 root root        33 Mar 15 14:49 libtensorflow_framework.so -> libtensorflow_framework.so.2.15.0
lrwxrwxrwx  1 root root        33 Mar 15 14:49 libtensorflow_framework.so.2 -> libtensorflow_framework.so.2.15.0
-r-xr-xr-x  1 root root  47893792 Mar 15 14:48 libtensorflow_framework.so.2.15.0
-r-xr-xr-x  1 root root    256786 Mar 15 14:15 libtensorflow_framework.so.2.15.0-2.params
drwxr-xr-x 15 root root      4096 Mar 15 14:16 lite
drwxr-xr-x  3 root root      4096 Mar 15 14:37 python
drwxr-xr-x  4 root root      4096 Mar 15 14:30 tools
[INFO] 
[INFO] --- exec-maven-plugin:3.1.0:exec (dist-download) @ tensorflow-core-native ---
[INFO] skipping execute as per configuration
[INFO] 
[INFO] --- maven-resources-plugin:3.3.1:resources (copy-resources) @ tensorflow-core-native ---
[INFO] skip non existing resourceDirectory /java/tensorflow-core/tensorflow-core-native/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:compile (javacpp-compiler) @ tensorflow-core-native ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 1 source file with javac [forked debug release 8] to target/classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] 
[INFO] --- exec-maven-plugin:3.1.0:exec (bazel-generate) @ tensorflow-core-native ---
[INFO] skipping execute as per configuration
[INFO] 
[INFO] --- javacpp:1.5.10:parse (javacpp-parser) @ tensorflow-core-native ---
[INFO] Skipping execution of JavaCPP Builder
[INFO] 
[INFO] --- build-helper-maven-plugin:3.4.0:add-source (add-gen-sources) @ tensorflow-core-native ---
[INFO] Source directory: /java/tensorflow-core/tensorflow-core-native/src/gen/java added.
[INFO] 
[INFO] --- maven-resources-plugin:3.3.1:resources (default-resources) @ tensorflow-core-native ---
[INFO] skip non existing resourceDirectory /java/tensorflow-core/tensorflow-core-native/src/main/resources
[INFO] 
[INFO] --- maven-resources-plugin:3.3.1:copy-resources (generated-resources-copy) @ tensorflow-core-native ---
[INFO] skip non existing resourceDirectory /java/tensorflow-core/tensorflow-core-native/src/gen/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.11.0:compile (default-compile) @ tensorflow-core-native ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 24 source files with javac [forked debug release 11 module-path] to target/classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /java/tensorflow-core/tensorflow-core-native/src/main/java/module-info.java:[28,6] [module] module not found: tensorflow
[WARNING] /java/tensorflow-core/tensorflow-core-native/src/main/java/module-info.java:[18,34] requires transitive directive for an automatic module
[WARNING] /java/tensorflow-core/tensorflow-core-native/src/main/java/module-info.java:[19,32] requires transitive directive for an automatic module
[INFO] 3 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[50,16] error: cannot find symbol
  symbol:   class TF_SessionOptions
  location: class AbstractTF_SessionOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[28,51] error: cannot find symbol
  symbol:   class TF_SessionOptions
  location: class AbstractTF_SessionOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[30,22] error: cannot find symbol
  symbol:   class TF_SessionOptions
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[52,16] error: cannot find symbol
  symbol:   class TF_Graph
  location: class AbstractTF_Graph
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[28,51] error: cannot find symbol
  symbol:   class TF_Graph
  location: class AbstractTF_Graph
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[29,22] error: cannot find symbol
  symbol:   class TF_Graph
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[50,16] error: cannot find symbol
  symbol:   class TFE_ContextOptions
  location: class AbstractTFE_ContextOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[28,51] error: cannot find symbol
  symbol:   class TFE_ContextOptions
  location: class AbstractTFE_ContextOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[30,22] error: cannot find symbol
  symbol:   class TFE_ContextOptions
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[18,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[18] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[45,9] error: cannot find symbol
  symbol:   class TF_Function
  location: class AbstractTF_Function
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[26,51] error: cannot find symbol
  symbol:   class TF_Function
  location: class AbstractTF_Function
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[28,22] error: cannot find symbol
  symbol:   class TF_Function
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/TFJ_RuntimeLibrary.java:[22,43] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[51,16] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class AbstractTF_Buffer
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[60,16] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class AbstractTF_Buffer
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[73,16] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class AbstractTF_Buffer
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[30,51] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class AbstractTF_Buffer
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[31,22] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[40,12] error: cannot find symbol
  symbol:   class TF_Tensor
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[51,43] error: cannot find symbol
  symbol:   class TF_Tensor
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[51,56] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[51,16] error: cannot find symbol
  symbol:   class TFE_TensorHandle
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[64,44] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[64,9] error: cannot find symbol
  symbol:   class TFE_TensorHandle
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[77,39] error: cannot find symbol
  symbol:   class TFE_Context
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[77,76] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[77,9] error: cannot find symbol
  symbol:   class TFE_TensorHandle
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[87,9] error: cannot find symbol
  symbol:   class TFE_TensorHandle
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[27,51] error: cannot find symbol
  symbol:   class TFE_TensorHandle
  location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[28,22] error: cannot find symbol
  symbol:   class TFE_TensorHandle
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Status.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Status.java:[56,16] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTF_Status
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Status.java:[35,51] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTF_Status
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Status.java:[36,22] error: cannot find symbol
  symbol:   class TF_Status
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[51,12] error: cannot find symbol
  symbol:   class TF_Graph
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[53,12] error: cannot find symbol
  symbol:   class TF_SessionOptions
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[54,12] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[55,12] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[56,12] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[67,38] error: cannot find symbol
  symbol:   class TF_Graph
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[67,54] error: cannot find symbol
  symbol:   class TF_SessionOptions
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[67,78] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[67,16] error: cannot find symbol
  symbol:   class TF_Session
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[84,6] error: cannot find symbol
  symbol:   class TF_SessionOptions
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[85,6] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[88,6] error: cannot find symbol
  symbol:   class TF_Graph
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[89,6] error: cannot find symbol
  symbol:   class TF_Buffer
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[90,6] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[83,16] error: cannot find symbol
  symbol:   class TF_Session
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[30,51] error: cannot find symbol
  symbol:   class TF_Session
  location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[31,22] error: cannot find symbol
  symbol:   class TF_Session
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[58,19] error: cannot find symbol
  symbol:   class Deallocator_Pointer_long_Pointer
  location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[76,16] error: cannot find symbol
  symbol:   class TF_Tensor
  location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[91,16] error: cannot find symbol
  symbol:   class TF_Tensor
  location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[108,9] error: cannot find symbol
  symbol:   class TF_Tensor
  location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[27,51] error: cannot find symbol
  symbol:   class TF_Tensor
  location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[28,22] error: cannot find symbol
  symbol:   class TF_Tensor
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[41,12] error: cannot find symbol
  symbol:   class TFE_ContextOptions
  location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[52,39] error: cannot find symbol
  symbol:   class TFE_ContextOptions
  location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[52,64] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[52,16] error: cannot find symbol
  symbol:   class TFE_Context
  location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[28,51] error: cannot find symbol
  symbol:   class TFE_Context
  location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[29,22] error: cannot find symbol
  symbol:   class TFE_Context
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[50,16] error: cannot find symbol
  symbol:   class TF_ImportGraphDefOptions
  location: class AbstractTF_ImportGraphDefOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[28,51] error: cannot find symbol
  symbol:   class TF_ImportGraphDefOptions
  location: class AbstractTF_ImportGraphDefOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[30,22] error: cannot find symbol
  symbol:   class TF_ImportGraphDefOptions
  location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[41,12] error: cannot find symbol
  symbol:   class TFE_Context
  location: class AbstractTFE_Op
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[52,29] error: cannot find symbol
  symbol:   class TFE_Context
  location: class AbstractTFE_Op
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[52,74] error: cannot find symbol
  symbol:   class TF_Status
  location: class AbstractTFE_Op
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[52,16] error: cannot find symbol
  symbol:   class TFE_Op
  location: class AbstractTFE_Op
[INFO] 100 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for TensorFlow Java Parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] TensorFlow Java Parent ............................. SUCCESS [  0.568 s]
[INFO] TensorFlow Core Parent ............................. SUCCESS [  0.009 s]
[INFO] TensorFlow Native Library .......................... FAILURE [33:55 min]
[INFO] TensorFlow Generators .............................. SKIPPED
[INFO] TensorFlow API ..................................... SKIPPED
[INFO] TensorFlow API Platform ............................ SKIPPED
[INFO] TensorFlow Framework Library ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33:56 min
[INFO] Finished at: 2024-03-15T14:49:08Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project tensorflow-core-native: Compilation failure: Compilation failure: 
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[50,16] error: cannot find symbol
[ERROR]   symbol:   class TF_SessionOptions
[ERROR]   location: class AbstractTF_SessionOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[28,51] error: cannot find symbol
[ERROR]   symbol:   class TF_SessionOptions
[ERROR]   location: class AbstractTF_SessionOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_SessionOptions.java:[30,22] error: cannot find symbol
[ERROR]   symbol:   class TF_SessionOptions
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[52,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Graph
[ERROR]   location: class AbstractTF_Graph
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[28,51] error: cannot find symbol
[ERROR]   symbol:   class TF_Graph
[ERROR]   location: class AbstractTF_Graph
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Graph.java:[29,22] error: cannot find symbol
[ERROR]   symbol:   class TF_Graph
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[50,16] error: cannot find symbol
[ERROR]   symbol:   class TFE_ContextOptions
[ERROR]   location: class AbstractTFE_ContextOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[28,51] error: cannot find symbol
[ERROR]   symbol:   class TFE_ContextOptions
[ERROR]   location: class AbstractTFE_ContextOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_ContextOptions.java:[30,22] error: cannot find symbol
[ERROR]   symbol:   class TFE_ContextOptions
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[18,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[18] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[45,9] error: cannot find symbol
[ERROR]   symbol:   class TF_Function
[ERROR]   location: class AbstractTF_Function
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[26,51] error: cannot find symbol
[ERROR]   symbol:   class TF_Function
[ERROR]   location: class AbstractTF_Function
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Function.java:[28,22] error: cannot find symbol
[ERROR]   symbol:   class TF_Function
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/TFJ_RuntimeLibrary.java:[22,43] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[51,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class AbstractTF_Buffer
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[60,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class AbstractTF_Buffer
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[73,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class AbstractTF_Buffer
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[30,51] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class AbstractTF_Buffer
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Buffer.java:[31,22] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[40,12] error: cannot find symbol
[ERROR]   symbol:   class TF_Tensor
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[51,43] error: cannot find symbol
[ERROR]   symbol:   class TF_Tensor
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[51,56] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[51,16] error: cannot find symbol
[ERROR]   symbol:   class TFE_TensorHandle
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[64,44] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[64,9] error: cannot find symbol
[ERROR]   symbol:   class TFE_TensorHandle
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[77,39] error: cannot find symbol
[ERROR]   symbol:   class TFE_Context
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[77,76] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[77,9] error: cannot find symbol
[ERROR]   symbol:   class TFE_TensorHandle
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[87,9] error: cannot find symbol
[ERROR]   symbol:   class TFE_TensorHandle
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[27,51] error: cannot find symbol
[ERROR]   symbol:   class TFE_TensorHandle
[ERROR]   location: class AbstractTFE_TensorHandle
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_TensorHandle.java:[28,22] error: cannot find symbol
[ERROR]   symbol:   class TFE_TensorHandle
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Status.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Status.java:[56,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTF_Status
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Status.java:[35,51] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTF_Status
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Status.java:[36,22] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[51,12] error: cannot find symbol
[ERROR]   symbol:   class TF_Graph
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[53,12] error: cannot find symbol
[ERROR]   symbol:   class TF_SessionOptions
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[54,12] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[55,12] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[56,12] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[67,38] error: cannot find symbol
[ERROR]   symbol:   class TF_Graph
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[67,54] error: cannot find symbol
[ERROR]   symbol:   class TF_SessionOptions
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[67,78] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[67,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Session
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[84,6] error: cannot find symbol
[ERROR]   symbol:   class TF_SessionOptions
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[85,6] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[88,6] error: cannot find symbol
[ERROR]   symbol:   class TF_Graph
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[89,6] error: cannot find symbol
[ERROR]   symbol:   class TF_Buffer
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[90,6] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[83,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Session
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[30,51] error: cannot find symbol
[ERROR]   symbol:   class TF_Session
[ERROR]   location: class AbstractTF_Session
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Session.java:[31,22] error: cannot find symbol
[ERROR]   symbol:   class TF_Session
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[58,19] error: cannot find symbol
[ERROR]   symbol:   class Deallocator_Pointer_long_Pointer
[ERROR]   location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[76,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Tensor
[ERROR]   location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[91,16] error: cannot find symbol
[ERROR]   symbol:   class TF_Tensor
[ERROR]   location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[108,9] error: cannot find symbol
[ERROR]   symbol:   class TF_Tensor
[ERROR]   location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[27,51] error: cannot find symbol
[ERROR]   symbol:   class TF_Tensor
[ERROR]   location: class AbstractTF_Tensor
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_Tensor.java:[28,22] error: cannot find symbol
[ERROR]   symbol:   class TF_Tensor
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[41,12] error: cannot find symbol
[ERROR]   symbol:   class TFE_ContextOptions
[ERROR]   location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[52,39] error: cannot find symbol
[ERROR]   symbol:   class TFE_ContextOptions
[ERROR]   location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[52,64] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[52,16] error: cannot find symbol
[ERROR]   symbol:   class TFE_Context
[ERROR]   location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[28,51] error: cannot find symbol
[ERROR]   symbol:   class TFE_Context
[ERROR]   location: class AbstractTFE_Context
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Context.java:[29,22] error: cannot find symbol
[ERROR]   symbol:   class TFE_Context
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[50,16] error: cannot find symbol
[ERROR]   symbol:   class TF_ImportGraphDefOptions
[ERROR]   location: class AbstractTF_ImportGraphDefOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[28,51] error: cannot find symbol
[ERROR]   symbol:   class TF_ImportGraphDefOptions
[ERROR]   location: class AbstractTF_ImportGraphDefOptions
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTF_ImportGraphDefOptions.java:[30,22] error: cannot find symbol
[ERROR]   symbol:   class TF_ImportGraphDefOptions
[ERROR]   location: class DeleteDeallocator
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[20,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[20] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[21,50] error: package org.tensorflow.internal.c_api.global does not exist
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[21] error: static import only from classes and interfaces
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[41,12] error: cannot find symbol
[ERROR]   symbol:   class TFE_Context
[ERROR]   location: class AbstractTFE_Op
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[52,29] error: cannot find symbol
[ERROR]   symbol:   class TFE_Context
[ERROR]   location: class AbstractTFE_Op
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[52,74] error: cannot find symbol
[ERROR]   symbol:   class TF_Status
[ERROR]   location: class AbstractTFE_Op
[ERROR] /java/tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/AbstractTFE_Op.java:[52,16] error: cannot find symbol
[ERROR]   symbol:   class TFE_Op
[ERROR]   location: class AbstractTFE_Op
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :tensorflow-core-native
```

Did I do something wrong? Or is this simply the current state of the repo, and needs fixes for the javaCPP bindings?

### PR DESCRIPTION
**Pull request by Craigacp**
The TSL headers are in a different source root in a Bazel build to the packaged whl files. This PR adds that source root to the JavaCPP generate task and modifies the preset to look for them in both places.

Fixes #529.

It also pulls in the start of some changes I was making to reduce the number of warnings from error prone, but I've not completed that yet.

### CODE REVIEW

File: tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/presets/tensorflow.java [hunk 1]
```diff
@@ -36,9 +36,11 @@
...
           compiler = "cpp17",
           include = {
-            "tensorflow/tsl/platform/ctstring_internal.h",
-            "tensorflow/tsl/platform/ctstring.h",
-            "tensorflow/tsl/c/tsl_status.h",
+            // TSL headers are in different places in a bazel build and the downloaded whl
+            // The lower part is still the same, so multiple roots are set in the pom file.
+            "tsl/platform/ctstring_internal.h",
+            "tsl/platform/ctstring.h",
+            "tsl/c/tsl_status.h",
```
Comment (karllessard) [inline tensorflow-core/tensorflow-core-native/src/main/java/org/tensorflow/internal/c_api/presets/tensorflow.java:43]: I don't see a root in the pom file that has the `tensorflow/` suffix, to replace the existing paths, is this still required?

**Review by karllessard — APPROVED** [review]
